### ISSUE TITLE
Add WAX as a valid network

### ISSUE THREAD

**Issue by MrToph** [dfuse-io/client-js#19]
As Dfuse partnered with WAX, it would be nice to just be able to write `wax` like you can currently do with `mainnet`, `jungle`, and `kylin`.

The host is [mainnet.wax.dfuse.io](https://developer.wax.io/dapps/dfuse-for-wax-dapps/)

```js
// i want to do
createDfuseClient({
    apiKey: DFUSE_API_KEY,
    network: `wax`,
    httpClientOptions: {
      fetch: nodeFetch
    }
  });

// I have to do
createDfuseClient({
    apiKey: DFUSE_API_KEY,
    network: `mainnet.wax.dfuse.io`,
    httpClientOptions: {
      fetch: nodeFetch
    }
  });
```

**Comment by maoueh** [comment]
We have deprecated support for shortcut version in `network` field completely instead. Everybody will need to provide the fully qualified endpoint when we remove support for it.
