### ISSUE TITLE
Suggestion apiRequest public method

### ISSUE THREAD

**Issue by mmcs85** [dfuse-io/client-js#2]
Can you guys make the apiRequest method public to reuse the same client to do HTTP request to proxy methods of a nodeos thru the dfuse endpoint?

It would keep the token updated

https://github.com/dfuse-io/client-js/blob/master/src/client/client.ts#L396

**Comment by maoueh** [comment]
I'm not against it for the actual concrete implementation but I'm more reluctant for the `DfuseClient` interface.

I think I'll do it.

**Comment by maoueh** [comment]
It's now publicly exposed so you can consume other proxied endpoint like `/v1/chain/get_info`. Release `0.2.0-rc.32` should contain this.

**Comment by mmcs85** [comment]
Thanks alot for this!
