### ISSUE TITLE
ApiRequest obfuscates nodeos like erros in DfuseAPiError

### ISSUE THREAD

**Issue by mmcs85** [dfuse-io/client-js#27]
ApiRequest obfuscates nodeos like erros if used to fetch or push a transaction using dfuse endpoint

The reason is the handling of DfuseApiError class
https://github.com/dfuse-io/client-js/blob/master/src/client/http-client.ts#L235

Example nodeos error and the "error" field with "code" and "what" is obfuscated.
{"code":500,"message":"Internal Service Error","error":{"code":3090005,"name":"irrelevant_auth_exception","what":"Irrelevant authority included","details":[{"message":"action declares irrelevant authority '{\"actor\":\"pixeos1issue\",\"permission\":\"issue\"}'; minimum authority is {\"actor\":\"pixeos1issue\",\"permission\":\"active\"}","file":"authorization_manager.cpp","line_number":534,"method":"check_authorization"}]}}

**Comment by maoueh** [comment]
Yeah that was meant to be used only for dfuse REST API error but now with `apiRequest` call. Should be easy to fix however. I'll try to find time to work on this.
