### ISSUE TITLE
Do graphql auto reconnects, if websocket connection gets closed?

### ISSUE THREAD

**Issue by BartolomeoItaliano** [dfuse-io/client-js#32]
Hi!
I am writing an app which needs to be up to date with eos blockchain and I am wondering, if I need to handle websockets closing on my end.

In other words: 
If websockets close for graphql query do they automatically reconnects if I use your library or I need to manually establish connection again?

Example query:
```
        const stream = await dfuseClient.graphql(`subscription {
                searchTransactionsForward(query: "receiver:eosio.token action:transfer", irreversibleOnly: false) {
                  cursor
                  trace {
                    matchingActions {
                      json
                    }
                  }
                }
              }`, (message) => {
            if (message.type === "data") {
                console.log(message.data);
            } else {
                console.log(message);
            }
        });

```

**Comment by maoueh** [comment]
Yes, it handles reconnection automatically as well as tracking the stream cursor, check https://github.com/dfuse-io/client-js#features for more features of the library.

Check never miss a beat GraphQL example for a more thorough example: https://github.com/dfuse-io/client-js/blob/master/examples/advanced/graphql-never-miss-a-beat.ts.

This is a bug tracker, questions and support request are best asked in our Telegram channel: https://t.me/dfuseAPI
