### ISSUE TITLE
Cannot write to $HOME

### ISSUE THREAD

**Issue by ekkis** [dfuse-io/client-js#5]
I'm deploying an app to the serverless Now platform where access to the $HOME directory is not allowed (/tmp is).  I am therefore running into an issue because `api-token-store.js` on line 146 tries to write to the home directory:
```javascript
super(`${homeDirectory}/.dfuse/${sha256sum.update(apiKey).digest("hex")}/token.json`);
```
would it be possible to pass an option to the `createDfuseClient` function indicating where an acceptable location for such storage may be?

if I submitted a PR would it have a reasonable chance of being accepted?

**Comment by maoueh** [comment]
It's already possible, you can specify the `apiTokenStore` instance to use. Simply use the `FileApiTokenStore` with a custom location:

```
import { createDfuseClient, FileApiTokenStore } from "@dfuse/client";

const client = createDfuseClient({
  ...,
  apiTokenStore: new FileApiTokenStore("/tmp/dfuse-token.json"),
  ...,
});
```

**Comment by maoueh** [comment]
Thanks for the report, I've added a note in the `API Token Store` section of the readme in the hope to helping others that would hit the same problem: https://github.com/dfuse-io/client-js/blob/master/README.md#api-token-store

**Comment by ekkis** [comment]
awesome.  thank you!
