### ISSUE TITLE
script does not terminate - how to properly shut down?

### ISSUE THREAD

**Issue by MrToph** [dfuse-io/client-js#6]
Hi, I'm using this client in a node.js script and my script never terminates because the refresh-scheduler has an open handle. (the setTimeout in @dfuse/client/dist/lib/client/refresh-scheduler.js:27)

Is there a proper way to tell the client to cleanup / disconnect / release resources?

**Comment by MrToph** [comment]
For now this hack does the trick:

```
dfuseClient.apiTokenManager.refreshScheduler.clearRefreshTimeout()
```

**Comment by maoueh** [comment]
Sure thing, definitely something we can fix up easily. I'll implement something shortly and check if there is not other handle leaks at the same time.

**Comment by maoueh** [comment]
0.2.6 has been released with the fix. You can now call `client.release()` which should clear out all hold resources.
